version: '3.8'

services:

#  inventoryService:
#    build:
#      context: ./
#      dockerfile: ./Dockerfile
#    image: inventory-service
#    ports:
#      - "8080:8080"
#      - "5005:5005"
#    environment:
#      DB_URL: mongo-db
#      DB_PORT: 27017
#      DB_USER: ${MONGODB_USR}
#      DB_PWD: ${MONGODB_PWD}
#      DB_NAME: ${MONGODB_NAME}
#    depends_on:
#      - mongo-db
#      - mongo-express

  mongo-db:
    image: mongo:4.1
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USR}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PWD}

  mongo-db-2:
    image: mongo:4.1
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    expose:
      - "27017"
    ports:
      - "27018:27017"

#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - "8081:8081"
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USR}
#      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PWD}
#      ME_CONFIG_MONGODB_URL: mongodb://localhost:27017,localhost:27018/admin?replicaSet=rs0&retrywrites=false
#    depends_on:
#      - mongo-db
#      - mongo-db-2