version: '3.8'

services:

  inventoryService:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: inventory-service
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      DB_URL: mongo-db
      DB_PORT: 27017
      DB_USER: ${MONGODB_USR}
      DB_PWD: ${MONGODB_PWD}
      DB_NAME: ${MONGODB_NAME}
    depends_on:
      - mongo-db
      - mongo-express

  mongo-db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USR}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PWD}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USR}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PWD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGODB_USR}:${MONGODB_PWD}@mongo-db:27017/
    depends_on:
      - mongo-db